### ISSUE TITLE
for games no parameters found

### ISSUE THREAD

**Issue by ravisairockey** [Paliverse/DualSenseX#10]
please help me how to let the demogame .rar be detected

**Comment by Paliverse** [comment]
Hello, Please download the game from here: https://paliverse.itch.io/dualsensex-game-demo
Scroll all the way down until you see the Big red Download Button.
Oncec you download, extract it with winrar or 7-Zip, make sure DualSenseX is installed, then just run the game, it should auto connect to the controller. If you're still having issues, please join the discord to get more help
