### ISSUE TITLE
[BUG]: controller emulation fails 

### ISSUE THREAD

**Issue by Supercoolguy769** [Paliverse/DualSenseX#100]
**Describe the bug**
This bug only effects one game and that is Forza horizon 5 for some reason the bug only happens while wired what the bug dose is make the game switch from controller to keyboard after using the controller and sometimes it fails to tell the game to do something and makes the game unplayable this only happens while wired   

**To Reproduce**
1. Use controller wired 
2.  Go on forza 5 
3. use controller 
4. drive a car

**Comment by DashCruft** [comment]
Are you using PS4 emulation instead of Xbox? Forza only works with Xbox emulation

**Comment by Supercoolguy769** [comment]
No i am using the xbox emulation

**Comment by DashCruft** [comment]
Did you install both of the drivers mentioned in order for DualSense to emulate correctly

**Comment by Supercoolguy769** [comment]
I did not at first but i still got the bug afterwards

**Comment by Paliverse** [comment]
Try this: https://www.youtube.com/watch?v=1LfwmiRUMTU

If you've tried the method in the video and does not work, you could try this:

Press the windows button -> search for `Set up USB Game Controller` -> click advanced button -> in the preferred device section set `Controller (XBOX 360 For Windows)` as the proffered device -> Press OK -> Try game
