### ISSUE TITLE
[Feature Request]: Let the game control the light bar

### ISSUE THREAD

**Issue by FoleyRose** [Paliverse/DualSenseX#101]
In some games, certain contexts can change the color of the light bar.  For example, in Hades, choosing a certain boon from a god makes the light bar change to the color associated with that god.

**Comment by Paliverse** [comment]
The app has no idea what happens in games, so can’t really set different lights based on what’s happening, I will be looking into some libraries that uses the lights to set mouse and keyboard, it could potentially be the same result in supported games.
