### ISSUE TITLE
[BUG]: Не могу просмотреть оверлей и уровень заряда батареи 

### ISSUE THREAD

**Issue by shpul9** [Paliverse/DualSenseX#103]
![Screenshot_1](https://user-images.githubusercontent.com/97921169/149844184-ff62449d-3b17-4151-9a6b-4d6358705cb3.jpg)

**Comment by DashCruft** [comment]
Please use english language in order to report a bug or ask a question.

Thank you

**Comment by Ivan-Alone** [comment]
Оверлей и дополнительная информация пока что не реализованы. 
Уровень батареи все программы для DualSense читают из одного и того же байта в HID-ответе (все основываются на коде оф. драйвера DS под линукс), и все успешно показывают ерунду. Это косяк не программ, а Sony и отсутствия документации. Может, когда-нибудь выпустят обновление прошивки, либо обновят драйвер под Linux с корректным считыванием, тогда уровень батареи будет показываться адекватно. Но точно не сейчас.
Короче - функция из первого вопроса будет реализована позже, второй вопрос ни о чём, решить его невозможно, пока в этом не поможет Sony.

(Will duplicate queston and my answer in english:)
Question: Can't open overlay and check battery level
My answer: Overlay and additional info are not realized yet. 
Each software for DualSense gets battery level from same byte in HID report (based on source of official Linux driver for DS), and each shows randomly data. It's not a error in programs like DSX, it's mistake made by Sony and absence of any documentation. May be they will realize firmware update, or will update Linux driver with correct reading, then battery level will shows normally. But not now.
Shortly - first question feature will realized later, second question is unsolveable before Sony actions.

**Comment by DashCruft** [comment]
Yes. The battery level is only an estimate/not accurate because of the bad engineering on Sony's side regarding the battery level on other devices such as iOS and Personal Computer. While that's unfortunate, the most accurate you can get is by having a PS5 console and checking the battery there.

**Comment by Paliverse** [comment]
Yeah it’s messed up, it’s at least better on mac, seems to be the most accurate, however there are sometimes small jumps in numbers but still better than what’s available on pc/Linux
