### ISSUE TITLE
[BUG]: HidHide NOT WORK

### ISSUE THREAD

**Issue by SiTWulf** [Paliverse/DualSenseX#104]
**Describe the bug**
Duplicate Gamepad (Sony and Xbox)

**To Reproduce**
1. Install HidHide (Restart after install)
2. Turn ON DualSense
3. You Get duplicate Gamepad, you can check in joy.cpl

**Expected behavior**
Only show one GamePad Xbox360

**Additional context**
Windows 11 21H2 22000.438 MainBuild
DualSense
HidHide 1.1.50.0

I not see any option in DualSenseX for Hide Joypad.

**Comment by Paliverse** [comment]
Temporarily disabled. Will come back in next version
