### ISSUE TITLE
Two controllers in steam [BUG]: 

### ISSUE THREAD

**Issue by Nestorfield** [Paliverse/DualSenseX#108]
**Describe the bug**
Hi, i have two controllers in steam when i am using your program, i am using wired connection, i'm trying to get to work dualsense in detroit become human with working touch screen, ps4 prompts etc.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![Screenshot 2022-01-23 143640](https://user-images.githubusercontent.com/98246491/150663807-56cbb3a1-c0a3-49be-9970-689e9b5a1973.png)

**Comment by Paliverse** [comment]
HidHide that would hide the DualSense Controller was temporarily disabled, will be back in the next update version 1.5.0
