### ISSUE TITLE
[BUG]: App forces 60hz render speed on Freesync/G-SYNC displays with high refresh rates

### ISSUE THREAD

**Issue by docmars** [Paliverse/DualSenseX#111]
### Describe the bug
I noticed whenever I'm using the app, my mouse cursor speed drops to 60fps, even though my display is set to 120hz. Everything is zippy fast until I bring DualSenseX up and there's a noticeable change in frame rate. Not a huge deal, just something I noticed that makes using the app feel a little jarring. It's like having a car downshift unexpectedly and everything feels weird.

### To Reproduce
1. Hook up a 120hz or higher display if you have one
2. In Windows, set your Display settings to your native resolution and 120hz refresh rate (Advanced Settings)
3. Use your computer normally with full buttery smoothness
4. Open DualSenseX and move your cursor around
5. See subtle flickering on screen (depending on display), and noticeable drop in framerate for mouse movements and dragging the app's window around

### Expected behavior
Same buttery smoothness as any other app

**Comment by Paliverse** [comment]
Hmm, as of this moment, im not sure how to adjust to higher refresh rate as currently i only have a 60hz monitor, if it's very bothersome, you can disable Touchpad to Mouse in Settings -> Controller Settings -> Touchpad to Mouse. I do plan to get a higher refresh rate monitor, so until then, not much i can do.

**Comment by docmars** [comment]
@Paliverse No worries! Not a showstopper, and it would be kind of difficult to test without a higher refresh rate to see things with.

The app doesn't make the mouse cursor laggy across the whole machine, only when the DualSenseX window is on-screen. This is because UWP apps utilize the GPU to render themselves, but for some reason it's locking the rendering frame-rate. There could be a V-Sync or frame limiter configuration you could change in your app's build settings. I'm not familiar with developing for Windows, but this seems like the thing to look for. 👍

**Comment by Thmyris** [comment]
Have the same problem on current steam version. When the app is in focus it creates a slight strobing effect on desktop. Monitor has freesync on. Not that important, but I wanted to report another case.
