### ISSUE TITLE
[BUG]: Arrow keys doesn't work as intended when using DS4 emulation in God of War

### ISSUE THREAD

**Issue by Fahaddz** [Paliverse/DualSenseX#112]
When using DS4 emulation in God of War, the arrow keys in menus skip through the options very fast. Even if I tap it once gently.
But when switching to 360 emulation, it works as intended.
Here is a video

https://user-images.githubusercontent.com/47282284/151316253-178b4acb-1b63-4632-9ed9-3d9acdc4bad0.mp4

**Comment by Paliverse** [comment]
How odd, i just tested, seems to work fine for me.

## Things to try:
1. Reinstall ViGEm Drivers
2. If playing through steam, make sure you disable steam input for the game by doing the following:
* Steam -> Library -> Game -> Gear Icon  -> Properties -> Controller -> then select "Disable Steam Input" from the dropdown
3. You can try to delete the save file and app settings for DSX, go to C:\temp then delete the folder named `DualSenseX`

**Comment by zhekaso** [comment]
Notice same issue in "non-steam" God of War. Hard to navigate in menu, and 'X' 'O' buttons often  processed by the game twice(
