### ISSUE TITLE
[BUG]: High CPU Usage while idling randomly

### ISSUE THREAD

**Issue by SeDi343** [Paliverse/DualSenseX#116]
**Describe the bug**
High CPU Usage while idling randomly.

**To Reproduce**
Occurs sporadically. Need to reopen DualSenseX to fix.

**Expected behavior**
Not a CPU usage of 100% on one core!

**Screenshots**
![image](https://user-images.githubusercontent.com/3628936/152624937-8b980477-43a6-435b-bc5e-e5b26be5838f.png)

**Additional context**

**Comment by Paliverse** [comment]
Everyone has a differnt PC setup, it's impossible to cater to every type of build.

**Comment by SeDi343** [comment]
Nice support. System used is a R9 3900x 32GB 3600MHz and RTX3090. If you care about your community.
