### ISSUE TITLE
[Feature Request]: Separately configuration for Bluetooth and USB connections.

### ISSUE THREAD

**Issue by Ivan-Alone** [Paliverse/DualSenseX#117]
It is necessary to add the ability to separately configure Bluetooth and USB connections.

Some games (such as Genshin Impact) only supports one of the DualSense connection types: USB only or Bluetooth only (99% first).

Example. I play via Bluetooth with DualShock emulation, the battery in the gamepad has run out and it turned off. I connect it via USB and the DSX continues to emulate DualShock, but the game can see two gamepads now (HidHide cannot work normally, and in general this is not the best solution - hiding something hardware from the system), respectively, and it listens all double clicks from real DS and fake DS4.

It would be nice if it would be possible to enable emulation only for a Bluetooth connection, and disable it when connected via USB, and vice versa.

I think this is not too difficult to do, so I would like to see such functionality in this wonderful program.

P.S. It would be even better to add the ability to emulate USB Dualsense when connected via Bluetooth (for games that could to handle only wired connection), but I know that this is not possible, because ViGEmBus does not support DualSense emulation (yet).

**Comment by Paliverse** [comment]
I mean you can just set the emulation to off mode when you switch between BT and USB. In the next update, switching emulation won’t require a restart anymore so it would make it easier for you

**Comment by Ivan-Alone** [comment]
YES, it is that thing I tell about. I need switch emulation manually, so it not comfort, isn't it? 
Anyway, if you don't want do that - so, okay, it's your opinion as developer

**Comment by Paliverse** [comment]
I mean it could be possible when using multiple profiles, and have button combinations to switch between profiles.

**Comment by Paliverse** [comment]
But that isn’t implemented yet
