### ISSUE TITLE
[BUG]: <Load last active trigger on start> does not work with <Bow> Mode

### ISSUE THREAD

**Issue by LorkHang** [Paliverse/DualSenseX#118]
**Describe the bug**
-Apply < Bow > mode is working but the settings do not save after restarting DualSenseX. Trigger behave as < Normal Trigger > on start.
-All 3 Apply Mode options with < Bow > are not saved on the next start

**Comment by LorkHang** [comment]
Yes, it is toggled On. I've tried to re-enable it as well.
Tired < Resistance , Gamecube , Soft trigger > , these modes are saved without issue, but not Bow Mode.

Awesome app, shame I didn't find this app sooner!!

**Comment by Paliverse** [comment]
Okay this will be handled in the next update :)
