### ISSUE TITLE
the main backlight of the gamepad does not work after restarting the computer

### ISSUE THREAD

**Issue by RITYAL** [Paliverse/DualSenseX#12]
I use your program to configure the backlight, because your program is the most convenient to configure, but after restarting the computer, the backlight turns off and you have to disconnect and reconnect the gamepad. In this case, the charge indicators are on and they can be adjusted, but unfortunately not the main backlight. I would really like you to fix this. after fixing this error, I think your program will be almost perfect!

**Comment by Paliverse** [comment]
Hello, ill look into this issue and investigate it
