### ISSUE TITLE
[Feature Request]: Windows tray battery percentage icon

### ISSUE THREAD

**Issue by JSlaig** [Paliverse/DualSenseX#120]
Basically we can't really know how much battery the controller has apart from the led indicator that you can enable in the app. Having an icon on the icon tray on the windows taskbar would be really useful even though in fullscreen games we can't really see it. 

I think it would be a really good quality of life improvement for the app, which is pretty dope so far!

**Comment by Paliverse** [comment]
I mean you can right click the current tray to see the percentage. I’m not sure if I want to create a separate one just for battery, I’ll look into it.
