### ISSUE TITLE
[BUG]: Discord link not working 

### ISSUE THREAD

**Issue by kireita** [Paliverse/DualSenseX#122]
**Describe the bug**
Discord  invite not working.

**To Reproduce**
1. Open app
2. Go to Info
3. Click on 'Join Discord Community'

**Expected behavior**
Open browser with discord invite

v1.4.9

**Comment by Paliverse** [comment]
Hello, thanks for reporting, I’ll investigate this soon!

**Comment by Paliverse** [comment]
Saw the issue, fixed for the next version
