### ISSUE TITLE
[BUG]: Multiply button calls on a single click

### ISSUE THREAD

**Issue by mirterious** [Paliverse/DualSenseX#123]
**Describe the bug**
Bug appeared in the God of War (non-steam) game. When the `dualshock 4` emuilation is turned on buttons behaivior becomes weird. However, when Xbox 360 emulation is up everything works fine.

1. Open the application;
2. Choose DualShock 4 emulation;
3. Open the game;
4. Use right stick or "down"/"up" buttons to choose menu items / Start a game and click "options" and then L1/R1

Even in the main menu bug appears - on a single click on "down

**Expected behavior**
Menu items should be switched one by one. Other stuff too.

**Additional context**
[Here](https://youtu.be/9S70A4MrVqc) is the video.

**Comment by Zandarck** [comment]
Does the game recognise the DualSense controller without using DSX? To me, it looks like ghosting (by recognising the DualSense and the emulated DS4), although I would've thought it would've done the same with the emulated 360.

**Comment by mirterious** [comment]
> Does the game recognise the DualSense controller without using DSX? To me, it looks like ghosting (by recognising the DualSense and the emulated DS4), although I would've thought it would've done the same with the emulated 360.

It doesn't work without the DualSenseX at all.

**Comment by Paliverse** [comment]
This is due to HidHid being disabled, it’s coming back in the next update 1.5.0 with much improvements

**Comment by KrisCris** [comment]
Is there an ETA for 1.5?

> This is due to HidHid being disabled, it’s coming back in the next update 1.5.0 with much improvements

**Comment by Paliverse** [comment]
Can’t give a concrete answer, but within this month, should be possible. Will be posting a beta for 1.5.0 before there is a release

**Comment by KachraSeth28** [comment]
Hi,

Even I faced the similar issue. However, I fixed the issue by limiting the fps to 60-70.

**Comment by mirterious** [comment]
> Hi,
> 
> Even I faced the similar issue. However, I fixed the issue by limiting the fps to 60-70.

That worked out for me too. Thanks
