### ISSUE TITLE
[BUG]: the ps5 controller cannot  be disconnected from pc with (ps+menu) button through BT

### ISSUE THREAD

**Issue by kimycai** [Paliverse/DualSenseX#127]
it worked fine when  I use DS4Windows,but not working in DualSenseX,so I should turn off the pc to disconncet the controller.
what's wrong with my controller?
Is there any way to turn off the controller?

**Comment by Paliverse** [comment]
There’s no reason you need to submit more than one issue for the same thing, don’t. 

You can hold the PS for 10 seconds to turn it off. Next update there will be option to select how you want to turn it off.

**Comment by kimycai** [comment]
sry for that 
thx!
