### ISSUE TITLE
[BUG]: Controller not detected in Elden Ring

### ISSUE THREAD

**Issue by mavanmanen** [Paliverse/DualSenseX#130]
**Describe the bug**
After following the instructions to install DualSenseX, doing a reboot and configuring the controller, Elden Ring does not recognise any inputs. This has been tested with both X360 and DS emulation. It does work in other games. I hope you can help me troubleshoot what is going wrong.

**To Reproduce**
1. Follow install instructions, reboot
2. Launch game

**Expected behavior**
Elden Ring detecting inputs.

**Comment by Paliverse** [comment]
If it works with other games but not elden ring, then the game is at fault. This isn’t a bug and out of my control. Report to elden ring devs for bad controller support

**Comment by nexterot** [comment]
If you fully and correctly emulate the XBOX controller, it should be working everywhere. Elden ring do work with a real XBOX gamepad.

The "Sekiro: Shadows Die Twice" game (on the same game engine, non-steam version) is also confirmed to be non-working.

**Comment by nexterot** [comment]
OK, the solution is to install HidHide. It seems like From Software's games only look for the first gamepad available.
