### ISSUE TITLE
[BUG]: Audio haptics does not work with surround sound

### ISSUE THREAD

**Issue by aaronth07** [Paliverse/DualSenseX#131]
**Describe the bug**
When using a surround sound input (either with a real surround sound setup or surround virtualization), audio haptics will not work.

**To Reproduce**
1. Use a surround sound device as default, or use virtualization such as Windows Sonic.
2. Enable haptics in settings like normal.
3. Test haptics using any audio (surround sound or stereo).
4. No haptics are felt.

**Expected behavior**
Haptics should be felt on the controller like normal.

**Comment by aaronth07** [comment]
I see this has been marked as closed. Does this mean this has been fixed or changed? Or ignored?

**Comment by Paliverse** [comment]
Sorry not ignored, but this will be looked at soon, it’s hard for me to test because I don’t have a surround sound setup

**Comment by phildong** [comment]
has this been fixed in the github/steam version? This is a deal-breaker for me. If it's fixed in the steam version I'll happily get it.
