### ISSUE TITLE
After using this app, redirecting audio to the controller now has the audio coming out of the controller speaker?

### ISSUE THREAD

**Issue by aaronth07** [Paliverse/DualSenseX#132]
It seems after using this app, I can no longer use my standard method of redirecting voicemeeter input into the controller. What used to happen was that redirecting the sound input through voicemeeter would enable sound based haptics on the controller. After testing this application, all sound redirected to the controller now is played through the controller's speakers, rather than used only for haptic feedback. This only happened after testing this app, so it must be something this app did, some setting it changed. Can someone help in getting it back to how it was before?

**Comment by aaronth07** [comment]
Uninstalling the device and re-adding it seems to have fixed it. Still weird that this happened in the first place though?

**Comment by Paliverse** [comment]
Could be a bug
