### ISSUE TITLE
Audio haptics not working and suggestions

### ISSUE THREAD

**Issue by THECOOLKID-boop** [Paliverse/DualSenseX#134]
Audio haptics dont work repeatedly,no matter what i do.
Also add all types of adaptive triggers and full haptic support

**Comment by Paliverse** [comment]
Make sure you’re connecting to the app with a usb cable. BT doesn’t work.

**Comment by THECOOLKID-boop** [comment]
Still doesnt workSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Paliverse ***@***.***> Date: 3/12/22  7:26 PM  (GMT-06:00) To: Paliverse/DualSenseX ***@***.***> Cc: THEOCULUSDRAGON ***@***.***>, Author ***@***.***> Subject: Re: [Paliverse/DualSenseX] Audio haptics not working and suggestions (Issue #134) 

Make sure you’re connecting to the app with a usb cable. BT doesn’t work.

**Comment by THECOOLKID-boop** [comment]
> Make sure you’re connecting to the app with a usb cable. BT doesn’t work.

Still doesnt work
