### ISSUE TITLE
[BUG]:Audio haptics not working

### ISSUE THREAD

**Issue by THECOOLKID-boop** [Paliverse/DualSenseX#135]
**Describe the bug**
Audio haptics only work sometimes even after a unplug,replug,app restart,pc restart

**To Reproduce**
1. Open Dualsense x app
2. Enable audio haptics
3. When doesn't work try everything
4. Still doesn't work
5. 5.restart pc
6. Open app again
7. Still doesn't work

**Expected behavior**
Audio haptics expected to work for all audio especially when switching to different audio types without a replug or pc restart

**Comment by orangpelupa** [comment]
Workaround.

After enabling audio haptics. Adjust the delay up / down.
