### ISSUE TITLE
Crashes When opened[BUG]: 

### ISSUE THREAD

**Issue by BoxChow** [Paliverse/DualSenseX#136]
Everytime I open it or when I start up my pc the program crashes and my controller wont connect

**Comment by Paliverse** [comment]
Try to delete the save folder located in C:\Temp\ named DualSenseX then start the app

**Comment by Leonm99** [comment]
i have the same problem, the controller wont connect with dualsensex and itll eventually crash. after deleting the temp folder the app itself works but it wont pick up the controller still.

**Comment by Linkachus17** [comment]
> Try to delete the save folder located in C:\Temp\ named DualSenseX then start the app

Still didn't fix the issue for me

I tried Uninstall and Reinstall the DualSenseX but no luck

**Comment by AmariLuigi** [comment]
Same for me, I have this issue too.
