### ISSUE TITLE
[BUG]: Bluetooth Inputs showing Xbox Prompts

### ISSUE THREAD

**Issue by angelo-ii** [Paliverse/DualSenseX#137]
When connected via cable, the controller shows PS5 prompts when you disable Playstation Controller support on steam in addition to emulating the DualSense controller as a DS4 controller. 

Would it be possible that this can be done but via bluetooth.

Eg games that show XBox inputs when or when not using cable: DarkSouls, Sekiro, Need4Speed Heat
Eg games that show PS inputs when using cable: Lego Star Wars SWS, Fallen Order, Rocket League, Witcher 3

**Comment by Paliverse** [comment]
Hello, natively supported games only work wired. And since there is no DualSense emulation, it’s not possible to do it via BT, however I know a DualSense emulation is in the works, just no eta
