### ISSUE TITLE
[BUG]: Mouse Cursor Moves Off-screen in DS4 Mode

### ISSUE THREAD

**Issue by Dragiron** [Paliverse/DualSenseX#139]
**Describe the bug**
Soon as I switch to DS4 emulation, my mouse cursor moves off to the right side of the screen and I can't do anything about it. I've tried toggling touchpad to mouse but the setting has no impact.

**To Reproduce**
1. Switch to DS4 emulation (I'm using USB connection if that matters)

**Expected behavior**
Expected to be able to use my mouse.

**Additional context**
On Windows 10, have a Logitech G502, and a standard Dualsense controller on USB connection.

**Comment by Paliverse** [comment]
hmmm, i've just tested, seems to be working fine on my end, i guess you can try deleting the save folder named DualSenseX, located at C:\Temp\ and then start the app again

**Comment by Dragiron** [comment]
Tried your suggestion to no avail. Did a little more research and discovered that Steam was the issue. Disabled all controller settings in Steam but there was no input detected. Also tried using HIDHide with no effect.  Switching back to 360 emulation I saw that DSX was picking up input again, switched back to DS4 and now it appears to work. Here's hoping PSNow plays nice.
