### ISSUE TITLE
Wrong key input

### ISSUE THREAD

**Issue by VictorCrispim** [Paliverse/DualSenseX#14]
I was testing this software but when i pressed INGAME X it reads O (xbox 306) if i switch to (dualshock4) some keys doesnt work.
If i press each key in the SOFTWARE it seems to read the right keys but, ingame is different.

It seems to happen in some games, the game i tested was Scarlet Nexus.

**Comment by Paliverse** [comment]
I tested both Xbox 360 and DualShock 4 using this: https://gamepad-tester.com/

Theres no issues with the buttons. Maybe its the game. Plus i havent changed anything when reading input from the controller and sending it to the emulation, as well as none else has complained about this issue. 

Try Rebinding the buttons within the game?
