### ISSUE TITLE
[BUG]: Configuration being replaced by something else? 

### ISSUE THREAD

**Issue by brunotdantas** [Paliverse/DualSenseX#140]
**Describe the bug**
With Steam closed the Game (in this case Lost In Random) doesn't detect DualSenseX configuration. 
It keeps blinking the control light. It seems that something is trying to override DualSenseX input. 

_**Important!**_ 
This doesn't happen with every game,  I played Darkest Dungeon for example and worked as expected as the screen shot below shows

**To Reproduce**
1. Close Steam
2. Open Game at gamepass that executes via EA App
3. See control light blinking trying to replace DualSenseX 

**Expected behavior**
Open the game and DualSenseX configuration works as expected

**Screenshots**
Initial stage
![image](https://user-images.githubusercontent.com/19207320/164315050-fa50c021-0574-4db9-9ed0-a441f104ff07.png)

When clicking anything at the controller
![image](https://user-images.githubusercontent.com/19207320/164315103-053db5ff-f51c-4b30-8e73-7d5b91987e17.png)

How the controller behave after clicking anything
https://youtube.com/shorts/3gsAjrf3kEw?feature=share

In another game
![image](https://user-images.githubusercontent.com/19207320/164316470-fae4d158-44c8-48c8-baaf-44900ccfb8c0.png)

**Additional context**

**Comment by Paliverse** [comment]
Hello, 

Thank you for the detailed Issue submitted! From the looks of it, something seems to be talking with the controller as well, could be the game, EA launcher, or steam or another program, it's hard to pinpoint.

To solve this issue, either manually Hide the physical controller with HidHide, or wait for the next update released on Steam where HidHide is integrated back into the app, and should solve your issue.

**Comment by brunotdantas** [comment]
> HidHide

Thanks I'll try and let you know if that worked as expected

**Comment by brunotdantas** [comment]
> Hello,
> 
> Thank you for the detailed Issue submitted! From the looks of it, something seems to be talking with the controller as well, could be the game, EA launcher, or steam or another program, it's hard to pinpoint.
> 
> To solve this issue, either manually Hide the physical controller with HidHide, or wait for the next update released on Steam where HidHide is integrated back into the app, and should solve your issue.

Thanks! I'll check how it goes and get back to you!

**Comment by Paliverse** [comment]
You can also use an older version like 1.4.7 that has HidHide integrated, but was removed due to some issues, but can still give it a try
