### ISSUE TITLE
[BUG]: Display stuttering 1.4.9

### ISSUE THREAD

**Issue by Yananisan** [Paliverse/DualSenseX#142]
Just downloaded the 1.4.9. Version. connected Dualsense and ran Detroit become human in Steam. PS buttons appeared and then changed with Xbox buttons with clicking on every new button. In game everything was with Xbox buttons. I swapped for ver 1.4.0 and now everything is fine.
I noticed that in Steam in 1.4.9 Version my physical PS5 controller was above PS4 emulator and in 1.4.0 PS4 is above PS5. Maybe because of that in 1.4.9 display is stuttering?
Maybe it will be better to hide physical appearance of controller when the emulator is running?

**Comment by Paliverse** [comment]
You'll need to use something like HidHide to hide the physical controller, it was removed due to some issues, but coming back in the next update releasing on steam.
