### ISSUE TITLE
gyro control cannot be set anywhere

### ISSUE THREAD

**Issue by karalrad** [Paliverse/DualSenseX#143]
There are no gyro controll settings.
Can you add this to next version?

**Comment by LoganDark** [comment]
Steam supports gyro control, even for controlling your mouse cursor. My only gripe is that you can't turn off Steam changing the color of the LED, so it keeps fighting with DualSenseX.

DualSenseX always wins though

**Comment by karalrad** [comment]
what about the cases when I play games for example from the Epic Game Store

**Comment by LoganDark** [comment]
> what about the cases when I play games for example from the Epic Game Store

Same thing. Go to Steam settings -> "Controller" in the sidebar-> "Desktop configuration" button. This will configure behavior outside of any Steam games.

You can configure a button to toggle the gyro in the additional settings of the gyro itself (don't remember the name, sorry).

**Comment by karalrad** [comment]
> > what about the cases when I play games for example from the Epic Game Store
> 
> Same thing. Go to Steam settings -> "Controller" in the sidebar-> "Desktop configuration" button. This will configure behavior outside of any Steam games.
> 
> You can configure a button to toggle the gyro in the additional settings of the gyro itself (don't remember the name, sorry).

This solution does not working

**Comment by LoganDark** [comment]
> This solution does not working

I don't have enough information to help you, sorry.

**Comment by karalrad** [comment]
When i want to play on Epic Game Store on for example Shadow od Romb Rider nothing working, i dont have any move in game, controls are dead

**Comment by Bekon241** [comment]
I wont write here coz i have smailar problem.
Game: 
Detroit: Being human
I play geme setup my ps5 controller as ps4 in emulator hidhiden on all setup ok i have problem only with gyro on controller i cant proper use move shake controller up or down but i shake it and somtime work and i stuck now becouse i cant do rotate... In game i not see any change color to blue even if i try meny gestures. Nothing happend look screen i pres L2 but i cant clockwhise move...
https://ibb.co/Jm27NvB
