### ISSUE TITLE
[BUG]: Buttons

### ISSUE THREAD

**Issue by BlackWhite16** [Paliverse/DualSenseX#144]
Hello, I have a problem in Detoit Become Human and in Forza Horizon 5, I turn on the emulation dualShock 4, when I turn the menu or play the game with a constant switching I get confused Ps and Xbox buttons, with Bluetooth no such problems, only wire, please help, I reinstalled windows, different drivers put, did not help

I uploaded the video:
https://drive.google.com/file/d/1gHtOENWBp01jT5NIGfM6N8oL65a1hb1M/view?usp=sharing

**Comment by Paliverse** [comment]
Hi, please refer to this video: https://youtu.be/1LfwmiRUMTU

**Comment by BlackWhite16** [comment]
Hi, I already did, it doesn't work. When I exit dualsenseX, the gamepad works in Xbox mode via USB, via Bluetooth it does not work in Xbox mode, what is the problem? No other software as i recently reinstalled windows
