### ISSUE TITLE
[BUG]: audio haptics is laggy 

### ISSUE THREAD

**Issue by orangpelupa** [Paliverse/DualSenseX#146]
**Describe the bug**
Enable audio haptics, and it's laggy no matter how the delay was adjusted 

**To Reproduce**
1. Enable audi haptics 
2. Adjust audio delay 
3. Adjust windows sound volume to make "ding" sound
4. Audio vibration delayed 

**Expected behavior**
It should have no delay or at least very small delay. Currently I'm using OBS audio monitoring feature for haptics audio, and it works with very minimal delay. 

**Screenshots**

**Additional context**

**Comment by Lucaspec72** [comment]
not sure if it helps, but from my observations the delay seems to be similar, if not equal to the delay bluethooth audio devices have, for some reason.

**Comment by Paliverse** [comment]
Not much i can do about this as some user's don't have any delays while others do. Not sure what the cause is. Will prob need to use a different Audio Library
