### ISSUE TITLE
Controller randomly acts like I'm pressing touchpad in No man's sky

### ISSUE THREAD

**Issue by dfgdgdgfd** [Paliverse/DualSenseX#147]
Connected via usb, gog version of the game.  I'm definitely not even getting close to touching it myself.  It's a bit annoying as it brings up the crafting/inventory menu which interrupts gameplay.  Haven't had this issue in any other games.

**Comment by Paliverse** [comment]
Seems like a game issue, not sure i can do anything about it, but make sure Touchpad to Mouse is turned off in controller settings, that could be the issue
