### ISSUE TITLE
[BUG]: I can't turn off gamepad emulation

### ISSUE THREAD

**Issue by qsdwart** [Paliverse/DualSenseX#153]
I can't turn off gamepad emulation

When I choose to emulate the controller I can click on xbox 360 and dualshock 4 but the OFF button doesn't work. I can't choose this.

![12](https://user-images.githubusercontent.com/79813206/175753650-7a44ae14-25de-4dd9-a59e-35c7d72030d6.png)

**Comment by Paliverse** [comment]
Yes there was an update that disabled it temporarily since it caused the controller not to be recognized by games, will be back when there’s a fix
