### ISSUE TITLE
Controller goes nuts and disconnects

### ISSUE THREAD

**Issue by lucasrsl** [Paliverse/DualSenseX#155]
This is happenning since the previous version, before Steam.
Sometimes the controller just stops responding to the commands and disconnects on its own.

**Comment by lucasrsl** [comment]
This video shows it happening.
The player on the left is the controller, I didnt touch the controller, and you can see it moving on its own and disconnecting and connecting over and over.


https://user-images.githubusercontent.com/28019044/176060814-caf4078e-81ee-4bd9-8fac-8a55463f1543.mp4

**Comment by Paliverse** [comment]
Try to reinstall the drivers!
