### ISSUE TITLE
What are the instructions for making the controller vibrate spontaneously?

### ISSUE THREAD

**Issue by marcosogsantos** [Paliverse/DualSenseX#156]
Your UDP example has references to changing the trigger behavior, RGB, and threshold. Still, I couldn't understand how to make the controller vibrate spontaneously, without the need to pull the trigger. Can you help me?

**Comment by Paliverse** [comment]
Vibration trigger only works when it's being pressed, it can't vibrate without pressing the trigger

**Comment by marcosogsantos** [comment]
So how does your software do this trick? 

![image](https://user-images.githubusercontent.com/51763881/177049963-def7c635-c8f3-411b-9163-b430e3a9dca3.png)
