### ISSUE TITLE
[Feature Request]: Make LED control - optional

### ISSUE THREAD

**Issue by BernykPavlo** [Paliverse/DualSenseX#157]
Some games sets LED colors depending on different conditions. For example in Marvel's Avengers LED color depends on currently chosen character. It has conflict with DualsenseX LED so gamepad LED is blinking. Please make an ability to turn off LED being controlled by app.

**Comment by Paliverse** [comment]
Latest version of DSX on steam has support for DualShock 4 LED passthrough, you can find it in the touchpad LED modes
