### ISSUE TITLE
[BUG]: trigger doesn't work in games

### ISSUE THREAD

**Issue by sid5648684** [Paliverse/DualSenseX#159]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sid5648684** [comment]
Wen i go to Dsx in the controller section and i pull the trigger, nothing happend contrary to the other buttons
![image](https://user-images.githubusercontent.com/108742147/177343871-e3dbfab3-8bd2-4c5e-bc1c-7be66c52e39b.png)
I test it in fall guys and it doesn't work either

**Comment by Paliverse** [comment]
Seems like you have a hardware issue. You might need to replace the broken trigger or take it somewhere to get it repaired
