### ISSUE TITLE
HAPTICS NOT LOADING & DSX LOADS WITH DISABLED VIBRATION

### ISSUE THREAD

**Issue by L10NHEART** [Paliverse/DualSenseX#161]
When plugging in controller the Haptics setting is shown as ON but don't work in game unless manually button is swtiched off then back ON.

When plugging in controller DSX loads with the setting "Disable controller vibration" set to ON even though I set it to OFF before unplugging controller.

**Comment by Paliverse** [comment]
Disable controller vibration has to be on when using Audio Haptics since normal rumble has to be disabled. I'll look into it for bugs
