### ISSUE TITLE
[BUG]: drivers doesnt work

### ISSUE THREAD

**Issue by VagonT** [Paliverse/DualSenseX#162]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by VagonT** [comment]
i download drivers 10 times and restart windows 5 times and drivers are missing 
![изображение](https://user-images.githubusercontent.com/108987575/178109105-c0cf2626-d8b9-4591-b35a-ea2fa1471ba5.png)

**Comment by VagonT** [comment]
also it cant find controller connected by USB 
![изображение](https://user-images.githubusercontent.com/108987575/178109192-42e17835-3374-4fcf-8ba7-99c0f6ad812a.png)

**Comment by MatheusOliveira08** [comment]
Same problem, it don't recognize the controller

**Comment by lizhulanov** [comment]
same problem

**Comment by InnocentClarke** [comment]
Drivers show as installed on my end, but it can't find the USB-connected controller either.

**Comment by Paliverse** [comment]
Best thing i can suggest is uninstalling the drivers first then install the latest from the github source mentioned above
