### ISSUE TITLE
[Feature Request]: Shutdown controller btn

### ISSUE THREAD

**Issue by fo0lman** [Paliverse/DualSenseX#164]
**Is your feature request related to a problem? Please describe.**
Controller loses battery level when controller is connected to PC and I not playing(

**Describe the solution you'd like**
Add controller shutdown button like on consoles

**Describe alternatives you've considered**
n/a. Switch bluetooth power on/off ? 

P.S. Press and hold PS button for 10 sec, it too long for me)

**Comment by Paliverse** [comment]
There's implamentation for turning off the controller with button presses, but that's only available on the Steam Version. Github version will no longer receive updates. You can see the steam version [here](https://store.steampowered.com/app/1812620/DSX/)
