### ISSUE TITLE
[8bitdo wireless adapter compatibility]: 

### ISSUE THREAD

**Issue by LucasNhoatto** [Paliverse/DualSenseX#165]
I'm having wireless connection problems, I use the 8bitdo adapter and the controller is not recognized.

When I use the 8bitdo wireless adapter on the PC the Dualsense is automatically recognized as an xbox 360 controller, there are also other pairing modes that even recognize the controller as a "wireless controller", but the DualsenseX does not connect it at all.

Sorry for any grammatical errors, I'm using a translator.

**Comment by Paliverse** [comment]
Hello, there isn't much i can do about this. From what i know, 8bitdo emulates an xbox controller, not sure about it's other mode. if it truly works as a regular "wireless controller" try re-installing the drivers
