### ISSUE TITLE
can't install it

### ISSUE THREAD

**Issue by Ravlyon** [Paliverse/DualSenseX#166]
![image](https://user-images.githubusercontent.com/22730941/181491635-1d97b4e8-dbc0-4fa4-a8b9-7b30c07a606b.png)
![image](https://user-images.githubusercontent.com/22730941/181491791-cf913924-c5d1-4bfa-95dc-6d9c45b1b424.png)
there is no selection to choose.

**Comment by Paliverse** [comment]
Try deleting the save folder named DualSenseX located in C:\Temp\
