### ISSUE TITLE
[BUG]: The gyroscope does not work in the steam version of dualsense x

### ISSUE THREAD

**Issue by YurvNick** [Paliverse/DualSenseX#167]
![image](https://user-images.githubusercontent.com/67200601/181839441-ce147ee0-dc32-4403-8106-12f00c64c859.png)
The gyroscope does not work in the steam version. I set the parameters the same as in the beta version and they don't work (( Is it possible to add a gyroscope implementation from the beta version, thank you

**Comment by Paliverse** [comment]
Gyro is only implemented for the DualShock 4 emulation as passthrough, also gyro isn't my main focus at the moment

**Comment by trustme6** [comment]
Gyro support and handling would be really nice

**Comment by Paliverse** [comment]
Will be worked on for v3 with proper motion data handling
