### ISSUE TITLE
[BUG]: steam 2.2.1: wrong battery LED color

### ISSUE THREAD

**Issue by thesourcehim** [Paliverse/DualSenseX#172]
**Describe the bug**
100% battery charge should be indicated by green LED color and it was before 2.2.1 update. Now it's yellow even when the battery is at 100% (indicator at the upper right corner of the window confirms that)

**Expected behavior**
LED should be green when battery is fully charged like it was before 2.2.1

**Screenshots**
![IMG_20220812_200348](https://user-images.githubusercontent.com/4952491/184408683-0c9c5f96-b4b9-4959-9773-6df3f7e059bb.jpg)

**Comment by Paliverse** [comment]
Will look into it

**Comment by thesourcehim** [comment]
Works properly in 2.2.2
