### ISSUE TITLE
[BUG]: Touchpad still acting as mouse

### ISSUE THREAD

**Issue by Jack-Batteries** [Paliverse/DualSenseX#186]
**Describe the bug**
I have turned off the option to use the touchpad as a mouse, yet it still acts as one and very slightly moves the cursor around without me touching either my actual mouse or the controller touchpad

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Controller'
3. Disable 'Enable Touchpad to mouse'
4. It still acts as a mouse and slightly shakes the cursor

**Expected behavior**
The touchpad should not do anything when I drag my finger on it and the cursor should not be shaking when the mouse is idling.

https://user-images.githubusercontent.com/44904150/188948151-e2a2df09-5126-40c9-977a-ba5698dd47f1.MOV

**Comment by Paliverse** [comment]
Hello,

Are you using the steam version or GitHub version of DSX?

**Comment by Jack-Batteries** [comment]
Yes I am, and now it only happens every now and then instead of all the
time.

**Comment by Paliverse** [comment]
That didn’t answer my question, but uhm you could try resetting app settings

**Comment by Jack-Batteries** [comment]
My bad, just saw this now. I am using the Steam version and the problem has
since been fixed so I do think that the app needed to be restarted.
