### ISSUE TITLE
Start ForzaDSX.exe flashback

### ISSUE THREAD

**Issue by Maikenene** [Paliverse/DualSenseX#187]
ForzaDSX flashes back when opening Forza4 after starting ForzaDSX.exe

**Comment by Maikenene** [comment]
After I started Forza DSX.exe, after launching Forza4, Forza DSX flashed back. Excuse me, what's the reason for this?

**Comment by Paliverse** [comment]
I don’t understand, what’s flash back?

**Comment by Maikenene** [comment]
It just quits automatically.
