### ISSUE TITLE
[BUG]: Приложение не работает.

### ISSUE THREAD

**Issue by roif7002** [Paliverse/DualSenseX#189]
Постоянно идет поиск контроллера! При подключении по блютус статус поиска иногда мигает, но все равно не находит!
При этом старая бесплатная версия работает нормально. В играх контроллер работает даже при закрытых приложениях. Но настроить геймпад соответственно не возможно!

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by roif7002** [comment]
> Постоянно идет поиск контроллера! При соединении по блютусу статус поиска иногда мигает, но все равно не находит! За то старая бесплатная версия работает нормально. В играх контроллер работает даже при закрытых приложениях. Настроить геймпад соответственно не возможно!
> 
> 4. См. ошибку
> 
> **Ожидаемое поведение** Четкое и краткое описание того, что вы ожидали.
> 
> **Снимки экрана** Если применимо, добавьте снимки экрана, чтобы объяснить вашу проблему.
> 
> **Дополнительный контекст** Добавьте сюда любой другой контекст проблемы.

**Comment by Paliverse** [comment]
English only please. I can’t speak Russian.

**Comment by roif7002** [comment]
Не надо говорить, включите переводчик и пишите!
