### ISSUE TITLE
[BUG]: У меня приложение просто не работает! Постоянный статус "идет поиск контроллера". При этом старая бесплатная версия работает нормально! Сделал возврат, его одобрили, но нужно ждать месяц!!!

### ISSUE THREAD

**Issue by roif7002** [Paliverse/DualSenseX#190]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Paliverse** [comment]
Well it’s too late to help you if you refunded already…

**Comment by roif7002** [comment]
Мне нужна не помощь, а работающее приложение!

пн, 12 сент. 2022 г. в 19:44, Paliverse ***@***.***>:

**Comment by roif7002** [comment]
Мне нужна не помощь, а работающее приложение!
