### ISSUE TITLE
Фейковое обновление[BUG]: 

### ISSUE THREAD

**Issue by roif7002** [Paliverse/DualSenseX#195]
Появилось обновление при открытии приложения. После его скачивания и перезагрузки все повторяется бесконечное количество раз. Обновление не вступает в силу, но окно с обновлением появляется снова и снова!**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Paliverse** [comment]
Как указано в примечаниях к патчу, это не обновление, а информация о DSX в Steam. Это также переводится

**Comment by roif7002** [comment]
как это убрать?

ср, 21 сент. 2022 г. в 12:27, Paliverse ***@***.***>:

**Comment by roif7002** [comment]
Что нужно сделать, чтобы платное приложение работало и находило контроллер?

ср, 21 сент. 2022 г. в 12:27, Paliverse ***@***.***>:
