### ISSUE TITLE
Зачем появилось окно обновления?[BUG]: 

### ISSUE THREAD

**Issue by ateisy** [Paliverse/DualSenseX#196]
Зачем появилось окно обновления, если само обновление не устанавливается и только затрудняет использование приложения?ribe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ateisy** [comment]
Я думал, что хорошая программа! Очень жаль!

**Comment by Paliverse** [comment]
It’s only to show info that DSX is on steam. It’s unfortunate it’s every time you launch the app, but you can ignore it if you want by hitting later on the pop up. It’s better you look up DSX on Steam and get the better upgraded version

**Comment by roif7002** [comment]
зачем тогда кнопка "да", означающая загрузить обновление, если оно не
работает?!!!

ср, 21 сент. 2022 г. в 22:11, Paliverse ***@***.***>:

**Comment by Paliverse** [comment]
It just installs the same 1.4.9 version again. So this pop up will not go away. It’s better than me removing all free versions and deleting them.

**Comment by Paliverse** [comment]
Oh sorry, I didn’t understand, however try installing the drivers again. Should fix the issue.

**Comment by roif7002** [comment]
я уже сделал возврат средств. Переустановка драйверов не помогла как и
многое другое!,

ср, 21 сент. 2022 г. в 23:28, Paliverse ***@***.***>:

**Comment by roif7002** [comment]
Зачем в окне бесплатной версии указана версия обновления 1.5.0 ?!!!

ср, 21 сент. 2022 г. в 23:38, Руслан Маслов ***@***.***>:

**Comment by roif7002** [comment]
Зачем тогда в окне указана версия обновления 1.5.0 ?!!!

ср, 21 сент. 2022 г. в 22:31, Paliverse ***@***.***>:

**Comment by ateisy** [comment]
Обман пользователей!!!

вт, 11 окт. 2022 г. в 11:28, Rolf ***@***.***>:
