### ISSUE TITLE
Update 1.5.0 annoying

### ISSUE THREAD

**Issue by PotatoDestroyer** [Paliverse/DualSenseX#198]
Can this stop??? every time I open the pc or the app. it shows.
I know there is a steam version, and I WILL NOT BUY IT.
so, stop this popup pls. or we need an ad block in apps nowadays?

![image](https://user-images.githubusercontent.com/47395819/191630515-cb38d76a-cda5-4efa-9449-2bbeb525cb84.png)

**Comment by Paliverse** [comment]
Sorry but there’s too many people that don’t know about DSX, so this is a way that just lets them know. Besides, better than deleting this free one from GitHub completely. I did spend thousands of hours making this App.
