### ISSUE TITLE
My controller won't stop detect as Mouse!

### ISSUE THREAD

**Issue by PoggersPlayer** [Paliverse/DualSenseX#20]
Hello! I was trying to connect my Controller, But It won't stop detect as Mouse! Instead, Left Analog Stick is Mouse Moving,
Cross is Mouse Click 1, Circle is Mouse Click 2!

**Comment by PoggersPlayer** [comment]
Oh! I won't detect as Mouse!!

**Comment by AzuraYasha** [comment]
Hi can you share how have you solved this problem? I have the same thing.
