### ISSUE TITLE
display stuttering

### ISSUE THREAD

**Issue by stevenstonie** [Paliverse/DualSenseX#21]
i noticed that after going from cable connection on my ps5 controller to wireless, the display started to stutter every few seconds.  This never happened before so it might be because of a new version of the program. I swapped for ver 1.3.3 and the problem disappeared. I usually spotted the micro-lag while playing games(no matter how demanding they were, so it wasnt a cpu/gpu problem) and it remained through usual stuff like browsing the web or meddling through the pc.

**Comment by Paliverse** [comment]
Hello, does this still happen?

**Comment by stevenstonie** [comment]
Hello,
    For the last 2 versions i didnt face any stutter.

**Comment by Paliverse** [comment]
okay im happy to hear that, will close this issue now
