### ISSUE TITLE
Controller not working on new update

### ISSUE THREAD

**Issue by Carabastin** [Paliverse/DualSenseX#22]
The controller isnt working on the new update for some reason even after reseting the pc, however it began working again after i installed the previous version

**Comment by RaidenRabit** [comment]
+1 on this, it gets stuck on the "Searching for Controller..." message for me. Even after unpairing/repairing, restarting the app, restarting pc, reseting the controller from that hidden button on the back.

**Comment by Paliverse** [comment]
I’ll try and investigate, honestly haven’t encountered this’d issue otherwise I wouldn’t update the app.

**Comment by tri4ng1e** [comment]
+1. On version 1.3.3, it seems to work fine. On version 1.3.6 I've got a continuous loop of "Connected" -- "Connection lost, searching for controller" messages with a period of around 1-3 seconds.

**Comment by Carabastin** [comment]
fixed by deleting save file for the app lol
