### ISSUE TITLE
[BUG]: dualsense - witcher 3 issue

### ISSUE THREAD

**Issue by iammr53** [Paliverse/DualSenseX#224]
When playing Witcher 3, a continuous clicking sound is heard in the dual sense. 
This does not stop and continues at a constant speed.

When I enter the cut scene or menu, this click stops, but when I return to the in-game, it starts again.

**Comment by Paliverse** [comment]
The Witcher 3 just got native support in their latest update, so both the app and the game are talking with the DualSense which makes it overlap. So you can just close DSX when playing a natively supported game.
