### ISSUE TITLE
[Feature Request]: Support for DualSense Edge PS5 Controller

### ISSUE THREAD

**Issue by andria-dev** [Paliverse/DualSenseX#234]
**Is your feature request related to a problem? Please describe.**
I just got the new DualSense Edge controller, and it doesn't seem to work with this application at all. It would be great if it did.

**Describe the solution you'd like**
I'd like the same or similar support as the DualSense controller.

**Describe alternatives you've considered**
The controller doesn't work wired or wireless for anything outside of steam.

**Additional context**
N/A

**Comment by Paliverse** [comment]
Hello, currently the version on steam has DS Edge detection and can be used. The GitHub version (free) is no longer being updated.

**Comment by andria-dev** [comment]
Ah okay, thank you for the info
