### ISSUE TITLE
[Feature Request]: Add shortcuts (i.e. to turn off the gamepad)

### ISSUE THREAD

**Issue by gezzior** [Paliverse/DualSenseX#239]
**Is your feature request related to a problem? Please describe.**
Not a huge problem, but turning the gamepad off requires you to hold the PS button for ~30 sec.

**Describe the solution you'd like**
I'd like to have a feature to turn off the gamepad after pressing a set combination of keys (for example PS + options).
I've used a similar software to yours, which had this feature. I prefer DualSenseX, but really miss a shortcut to turn off the gamepad quickly.

**Describe alternatives you've considered**
My only alternative is to install mentioned software.

**Additional context**
It would be cool if there would be more shortcuts to create (i.e. switch emulation, turn off the LEDs etc)

**Comment by Paliverse** [comment]
Hello, all of this is possible in DSX on steam.

**Comment by gezzior** [comment]
Perfect, was not aware. Thanks for your work!

**Comment by Paliverse** [comment]
Np, you can configure it in settings -> Controller -> Shortcuts. The default for turning off the controller is PS button + Triangle
