### ISSUE TITLE
HidHide driver problem

### ISSUE THREAD

**Issue by KRONE98** [Paliverse/DualSenseX#25]
I'm having an issue with the new driver requirement
I've installed the driver several times but dualsensex keep saying that I haven`t, I don't know if that it's normal or not
Also I'm having troubles with dualshock 4 emulation, the games that used to work before doesn't anymore, when I change it to xbox 360 emulation seems to work fine

**Comment by Paliverse** [comment]
Hello, the pop up has a bug, which has been fixed for the next update. It was checking the wrong thing to determine if HidHide was installed. For the second issue, im not sure why it wouldnt work, of course if the game nativly supports DualShock 4 Controllers, it should work fine, if not, you'll have to use Xbox 360 Emulation.
