### ISSUE TITLE
Question: haptic feedback speaker

### ISSUE THREAD

**Issue by DrifterMinas** [Paliverse/DualSenseX#26]
is there any way to make the haptic feedback speaker work?

**Comment by Paliverse** [comment]
Yes, there’s a way to enable the speaker and the headphone jack. But only when connecting through a USB Cable.

**Comment by Paliverse** [comment]
Will be adding within the next couple of updates, stay tuned

**Comment by Paliverse** [comment]
Speaker/Headphone jack is now enabled within the app (USB ONLY), as for haptic feedback not yet.
