### ISSUE TITLE
Rumble not working :(

### ISSUE THREAD

**Issue by Clickrouc** [Paliverse/DualSenseX#27]
Hello!
When I test your soft for Cyberpunk 2077, rumble not working with DualShock 4 / Xbox 360 config.
Sorry for my bad English, it's not my native language.

**Comment by Paliverse** [comment]
Hello, I’ll try to investigate this later today.

**Comment by Clickrouc** [comment]
Clarification: Sorry, I double-checked. Rumble does not work only in DS4 mode. In DS4Windows same issue.

**Comment by Clickrouc** [comment]
In xbox360 mode is work/

**Comment by Paliverse** [comment]
Another user has just tested the game and the vibration works with Xbox 360 Emulation. Please make sure in settings->Controller->Disable Vibration is NOT on. Make sure it’s off.

**Comment by Clickrouc** [comment]
Yes, with Xbox 360 Emulation ramble is work. But with DS4 Emulation don't :( Is it problem with ViGEmBus?

**Comment by Paliverse** [comment]
Not sure, also have the same issue with DualShock 4. So my advice is to use 360 emulations.

**Comment by Paliverse** [comment]
Also I think the game is the problem, not the emulation.
