### ISSUE TITLE
Double inputs

### ISSUE THREAD

**Issue by CurlySparkle** [Paliverse/DualSenseX#29]
For some reason, when using the DualShock 4 emulation setting, certain games will still display double inputs and sometimes causes problems like every time you press a button on the controller will either change to Xbox and PS4 inputs back and forth even still when the HidHide option is enabled, its weird because most games have support for PS controllers (Like it shows the PS4 buttons), the games affected when using this is, Detroit: Become Human (And other games from Quantic Dream like Heavy Rain and Beyond), Death Stranding, Crash Bandicoot 4, Psychonauts 2 and other games that don't wanna list otherwise would make a big wall of text.

**Comment by Paliverse** [comment]
hmm that's odd, have you rebooted after installing HidHide?

**Comment by CurlySparkle** [comment]
Yeah, after installing HidHide and restarting, doesn't seem to do much change, but its weird because when i test on other games, the PS4 inputs work fine without that issue where the xbox inputs appear and goes back in forth with the PS4 ones.

**Comment by Paliverse** [comment]
It’s very possible and likely that the game itself tries to read the controller and makes their own version of an emulation to work with the game, if you’re not seeing it on other games, the game is the issue.

**Comment by CurlySparkle** [comment]
I'll see, will do some more testing and see if there's a way to get around the issue.
