### ISSUE TITLE
В наушниках нет звука

### ISSUE THREAD

**Issue by Lekssl** [Paliverse/DualSenseX#31]
После не давноего обновления, пропал звук в наушниках, то есть я подключаю наушники и тут звук идет через контроллер а не через наушники. Исправте это пожалуйства, что бы был выбор! И пожалуйста сделайте совместимость со Steam буду очень благодарен!
Большое спасибо за вашу работу!

**Comment by Paliverse** [comment]
привет, в новом обновлении добавлены новые функции для соковыжималки и наушников, вы можете настроить их в настройках -> настройки контроллера.  если вы видите слова на английском, это значит, что они еще не переведены на русский язык.

**Comment by Paliverse** [comment]
были добавлены трансляции, перейдите в «Настройки» -> «Настройки контроллера» -> и установите режим вывода на динамик или гарнитуру.  ты можешь выбрать.

**Comment by Lekssl** [comment]
Нашел, просто там написано No Translation Found) Спасибо большое)

ср, 22 сент. 2021 г., 12:32 Paliverse ***@***.***>:
