### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Romz24** [Paliverse/DualSenseX#32]
Add the ability to change the font size. Due to the fact that some words are longer than English, they are not visible at all or climb out of the boundaries of the view. 

![image](https://user-images.githubusercontent.com/2458113/135584998-16b44218-c8df-428f-8c10-78b80bc391ab.png)
![image](https://user-images.githubusercontent.com/2458113/135583649-86033cb2-b8c1-42ea-992e-8e7a4ff84358.png)

**Comment by Romz24** [comment]
I also noticed that some places are not fully translated, there are no translation keys in the localization file. Can you add keys for translation?

![image](https://user-images.githubusercontent.com/2458113/135582441-95e1a5c1-d172-46d9-b8b2-3a67f18b1725.png)
![image](https://user-images.githubusercontent.com/2458113/135582579-af8681ea-bd2e-49ef-a4ac-8435a390e945.png)
![image](https://user-images.githubusercontent.com/2458113/135582702-d3011741-2b38-41a0-96d4-310d4dd97a4b.png)
![image](https://user-images.githubusercontent.com/2458113/135582763-bd23a1c9-bfae-47dd-b436-a4bc7250a84f.png)

**Comment by Paliverse** [comment]
Hello, having an overall system font size for the whole app is not a practical thing, but i will look for ways to see if i can add an auto font size to make the text fit in its width. and ill add the missing keys soon
