### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by hillboy2000** [Paliverse/DualSenseX#35]
It does not work in windows 11. Kept saying searching for controller on both USB and Bluetooth connections.

**Comment by Paliverse** [comment]
Have you installed Vigem? 

Take a look here: 

https://github.com/Paliverse/DualSenseX#download-and-install

**Comment by hillboy2000** [comment]
That worked! Thanks for the help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Paliverse** [comment]
Happy to help :)
