### ISSUE TITLE
It is not installed and does not start

### ISSUE THREAD

**Issue by DarkXPixel** [Paliverse/DualSenseX#4]
Hi, in short. First I installed it and everything was ok. Next, I went through the settings and turned off the gamepad emulation (Where Dualshoke and xbox 360 are). I got a blue screen of death. After restarting, it no longer started, or rather it started, but an error like'.', hexadecimal value 0x00, is an invalid character flew out. Line 1, position 1 (I tried reinstalling, everything is the same) . I assume that you need to delete the application config file. The problem is that I do not know where it is located
![Screen](https://user-images.githubusercontent.com/77230408/125158144-ae814f80-e177-11eb-9d76-e10e47395d7c.png)

**Comment by Paliverse** [comment]
Hello, I deeply apologize for this issue as I’m trying to wrap my head around what could be the issue, however it does look like something being Corrupt in the save file. Please try deleting the save file located in 'C:\Temp\DualSenseX\DualSenseX_SaveFile.xml'

and try again. You can even delete the whole folder as well if that helps, it will recreate it upon launching the app. It looks like some users are experiencing this rare bug that I’m unable to replicate, I will try to analyze and debug throughly to hopefully fix this issue in the near future.

**Comment by DarkXPixel** [comment]
Thank you, yes it helped, by the way, here is the whole folder: 
[DualSenseX.zip](https://github.com/Paliverse/DualSenseX/files/6795065/DualSenseX.zip)

**Comment by Paliverse** [comment]
Yeah it was the save file being corrupt for some unknown reason. I’ll try my best to get this resolved ASAP.

**Comment by Paliverse** [comment]
I beleive the bug has been fixed now.
