### ISSUE TITLE
Feature request: Trackpad as mouse input in desktop mode

### ISSUE THREAD

**Issue by Dysanix** [Paliverse/DualSenseX#40]
It would be very nice to add the ability to use the trackpad as a mouse while not in a game.
The trackpad would work like a laptop trackpad and a short click would be left click, long click would be right click.
This would open up the possibility to just sit on a couch lazily and launch a bunch of games from the controller without having to bring your mouse.

**Comment by yorai1212** [comment]
I'd love that!

**Comment by Paliverse** [comment]
Something I wanted to implement, just don’t know how, I’ll try and look into it

**Comment by Ivan-Alone** [comment]
This feature is just required to add, so will wait for updates. Maybe you can use mouse-touchpad realisation from DS4Windows? If I can understand, it has open source, so nobody can prohibit to get inspiration, or simple use parts of it's code.

**Comment by Paliverse** [comment]
Well good news. Literally in the middle of implementing it. 

![0DAC4CDC-742B-4E09-9839-C784609957AE](https://user-images.githubusercontent.com/4289084/147793821-3262be48-d400-4f7d-986f-fdcaf0546106.png)

It will be usable in this type of style, will also be button changeable for slow and fast sensi and right click. It will be coming in the next update

**Comment by DashCruft** [comment]
Isn't this suppose to be closed? 
The feature is added in the latest release (1.4.9) and it works totally fine

**Comment by Paliverse** [comment]
Ah forgot to close it, thanks for the reminder.
