### ISSUE TITLE
Emulating DualShock 4 doesn't work with any game

### ISSUE THREAD

**Issue by illyve1** [Paliverse/DualSenseX#43]
DPad is the only key getting recognized, but when pressed it, it keeps pressing infinitely even without touching the controller.

Some of these games do recognize the DualSense as a controller and work just fine, but when set to emulate DualShock 4 in DualSenseX it keeps doing the same bug.

It was working fine a few days ago, any idea what could possibly be going wrong?

https://user-images.githubusercontent.com/65648338/139795376-b01b0387-80e8-4da3-953f-96dd956c880c.mp4

Im using the controller wired btw

**Comment by Paliverse** [comment]
Hello, have you tried a different version?

**Comment by illyve1** [comment]
Yeah, after testing i discovered it works fine with the version 1.4.2, i'll be using this one for now. Thank you!

Somehow the bug is only happening in the newer version.

**Comment by Paliverse** [comment]
Thanks for the feedback, I’ll look into it
