### ISSUE TITLE
DualSensX crashes after turning on xbox 360 emulation

### ISSUE THREAD

**Issue by DanilMaximov** [Paliverse/DualSenseX#46]
Hey there, I'm facing a crashing of applications just after launch. It happened once I've reset my gamepad, then enabled Audio Haptics and switched to xbox360 emulation and after that followed crash and I'm not able to successfully launch DualSenseX since then :/

**Comment by Paliverse** [comment]
Hmm, that’s odd, could you try deleting the save data located in C:\Temp\DualSenseX, you can just delete the whole folder

**Comment by DanilMaximov** [comment]
> Hmm, that’s odd, could you try deleting the save data located in C:\Temp\DualSenseX, you can just delete the whole folder

Yeah, that worked for me, thank you :)
