### ISSUE TITLE
Having problem launching it on my 10 year old PC

### ISSUE THREAD

**Issue by Artyom-Krivosheev** [Paliverse/DualSenseX#47]
You have to dance with a drum perfectly, run it as administrator, disconnect the DualSense before the start and then, if I am lucky, it launches. Neither adaptive triggers, nor haptic feedback doesn't work for me (2 Vgmbus drivers requested I've already installed), wirelessly or wired. Idk, DS4Windows worked for me just fine but this one is pain in the bum

**Comment by Paliverse** [comment]
Uhm, I would recommend a more modern PC.
