### ISSUE TITLE
Control volume in Windows

### ISSUE THREAD

**Issue by stylianosnicoletti** [Paliverse/DualSenseX#49]
No able to control the volume via Windows, the volume settings in the app keep overriding windows volume.

**Comment by Paliverse** [comment]
Which voulume? Audio Haptics? reg Speaker?

**Comment by stylianosnicoletti** [comment]
When i set audio output to controller headset in your app, i can only control volume via the app, no matter what the windows master volume is. Lets say the windows volume is 40 %  for all devices (main) and the headset volume in your app is 80% i keep hearing in 80% volume. When i use volume up or down on windows keys i can hear a the differce on volume for 1 sec and then it goes back to what is set in your app volume.

**Comment by Paliverse** [comment]
oh okay, i understand now. I'll see what i can do about it. I'm currently trying to figure out the best way to handle all audio functionality in a good non complicated way. What you are mentinoing is possible though, to adjust the volume through windows.
