### ISSUE TITLE
Adaptive trigger issue when playing Metro Exodus PC Enhanced Edition 

### ISSUE THREAD

**Issue by codekenny2021** [Paliverse/DualSenseX#5]
Hi
When Dualsense X is opening and even turns every force setting to 0 from the custom trigger value(not using XBox360 emulation), there is a clear difference in terms of the adaptive trigger when Dualsense X is turned on and off.
Right now I need to close the Dualsense X when playing Metro Exodus PC Enhanced Edition to have the native feeling, 
could you please check or advise whether I should tune the setting?
Thanks.

**Comment by Paliverse** [comment]
Hello, i would recommend playing the game as native. Running both at the same time is just gonna  confuse the controller as both will be trying to communicate to the controller and will be a mess. Which part are you trying to access from the app while running the game?

**Comment by codekenny2021** [comment]
Hello

Thanks for replying. It just runs under the background, stimulating xb360
controller and using led color function. Thanks.


在 2021年7月23日週五 07:31，Paliverse ***@***.***> 寫道：

**Comment by Paliverse** [comment]
Yeah again, I don’t recommend running the Application when there is native support. It will just mess things up running both at the same time.
