### ISSUE TITLE
Xbox Game Bar

### ISSUE THREAD

**Issue by stylianosnicoletti** [Paliverse/DualSenseX#50]
Add an option to open "Xbox Game Bar" by pressing the "PlayStation" button, instead of the "Mic" + "Up" only.

**Comment by Paliverse** [comment]
I've tested with the PS Button, but cuases issues with steam's Biig Picture Mode getting turned on which could be an annoything to keep popping up

**Comment by stylianosnicoletti** [comment]
Aah i see okay thanks 😊
