### ISSUE TITLE
Audio Haptics and normal vibration from the game

### ISSUE THREAD

**Issue by Danil010302** [Paliverse/DualSenseX#52]
When Audio Haptics is turned on, normal vibration from the game is turned off, only Haptics works. Turning Disable Controller Vibrations on and off doesn't help, either Haptics or normal vibration works. Using VoiceMeeter works both Haptics and normal vibration from the game.

**Comment by Paliverse** [comment]
There is an option in Controller Settings where Disable Vibrations is located, "enable incoming vibration while disbled" It should be ticked on

**Comment by Danil010302** [comment]
Doesn't help anyway, only haptics works

Пн, 8 нояб. 2021 г. в 22:33, Paliverse ***@***.***>:
