### ISSUE TITLE
ui mess up !? help!!

### ISSUE THREAD

**Issue by whathuh** [Paliverse/DualSenseX#53]
<a href="https://ibb.co/L8z2TD8"><img src="https://i.ibb.co/L8z2TD8/20211109102324.png" alt="20211109102324" border="0"></a>

**Comment by whathuh** [comment]
i tried older version
but same problem

**Comment by Paliverse** [comment]
Delete the Folder located in C:\Temp named DualSenseX, you can just delte the whole folder. start the app again and after you select a language, just give it a sec

**Comment by whathuh** [comment]
<a href="https://ibb.co/nkWbFc5"><img src="https://i.ibb.co/nkWbFc5/20211110130103.png" alt="20211110130103" border="0"></a>
it doesn't work !
i can't even changing language . 
i think it's conecetion issues ! ?
does it work offline ?

**Comment by whathuh** [comment]
<a href="https://ibb.co/rMLZ3Md"><img src="https://i.ibb.co/rMLZ3Md/20211112014011.png" alt="20211112014011" border="0"></a>
yeap! it's conecetion issues !
