### ISSUE TITLE
No reset defaults/where is config file?

### ISSUE THREAD

**Issue by dfgdgdgfd** [Paliverse/DualSenseX#54]
I've uninstalled and reinstalled because I messed with the trigger thresholds but they didn't changed after opening up, after reinstall.  Deleting the leftover files in the program folder didn't work either.

**Comment by Paliverse** [comment]
hello, sorry for the delay! 

The save file is located in C:\Temp\DualSenseX\DualSenseX_Savefile.xml

you can Delete it, and restart the app if you're having issues.
