### ISSUE TITLE
Which adaptive trigger setting do I choose if a game natively supports it?

### ISSUE THREAD

**Issue by dfgdgdgfd** [Paliverse/DualSenseX#56]
I want to run games that support adaptive triggers and regular vibration but not haptic, but there doesn't seem to be a default/let the game decide option.  Also, for games that support haptics native, I disable vibration in the program, right?  And finally which controller do I choose to emulate in the above situations, dualshock 4 or none?

I tried assassin's creed valhalla but couldn't get either haptics or adaptive triggers working.  I'm also unsure what the point of setting haptics to audio output is, it works in all games but surely it isn't the same as native haptic support, or even regular vibration?

**Comment by Paliverse** [comment]
If you’re playing with a game that had native support, you should not be running DualSenseX. Because my app will constantly be communicating with the controller. Audio haptics is based on audio that is being played, the controller acts like a subwoofer, native games that use Audio Haptics just play a sound when they want the controller to vibrate from sound. I don’t see any advantages of having the app running when you’re playing a natively supported game.

**Comment by dfgdgdgfd** [comment]
> I want to run games that support adaptive triggers and regular vibration but not haptic, but there doesn't seem to be a default/let the game decide option. Also, for games that support haptics native, I disable vibration in the program, right? And finally which controller do I choose to emulate in the above situations, dualshock 4 or none?
> 
> I tried assassin's creed valhalla but couldn't get either haptics or adaptive triggers working. I'm also unsure what the point of setting haptics to audio output is, it works in all games but surely it isn't the same as native haptic support, or even regular vibration?

Ah ok, what would you recommend for using bluetooth for native games?  Adding them in steam and playing from there?

**Comment by Paliverse** [comment]
That would probably be your best bet, but steam can’t make the triggers and stuff work. Natively supported games are USB only.

**Comment by dfgdgdgfd** [comment]
> That would probably be your best bet, but steam can’t make the triggers and stuff work. Natively supported games are USB only.

Ok, what settings are best to get xinput vibration?  I tried setting to xbox 360 with vibration on, didn't feel anything in a game that supports a 360/one controller natively.

**Comment by Paliverse** [comment]
Hmm weird, should vibrate automatically. You checked in Controller Settings -> Disable Vibration is toggled off?

**Comment by dfgdgdgfd** [comment]
> Hmm weird, should vibrate automatically. You checked in Controller Settings -> Disable Vibration is toggled off?

Yes, do all other settings to do with haptics and audio need to be disabled too?

**Comment by Paliverse** [comment]
Uhm it’s up to you but not necessarily, for Audio Haptics to work, disabling vibration is required. For simple Audio playback through speaker or headset on the controller doesn’t need the vibrations to be disabled

**Comment by Paliverse** [comment]
I would suggest waiting for the next update as it fixes multiple issues, mainly the save file for the app which gets corrupted and might mess with how the controller behaves in games like the vibration for example

**Comment by TheCarrotCR** [comment]
> That would probably be your best bet, but steam can’t make the triggers and stuff work. Natively supported games are USB only.

Since DualSenseX works with triggers and stuff via bluetooth (does it? I haven't tried tbh), is it possible to implement wired mode emulation when wireless? It'll be great imo and no other program has this functionality yet.

**Comment by Logerfo** [comment]
Using DualSenseX to allow adaptive triggers to work with natively supported games when connected via bluetooth would be awesome.

**Comment by Paliverse** [comment]
Hello, currently not possible, maybe in the future
