### ISSUE TITLE
Synchronization with Steam

### ISSUE THREAD

**Issue by Ditaro31** [Paliverse/DualSenseX#58]
When I go to Steam through this program (using the joystick from PS 5), the Steam sees 2 joysticks at once (ps5 and ps4) and the usual actions are repeated. How to fix it?

**Comment by slovenec88** [comment]
I'm having the same issue on the latest version 1.4.5. I've tried disabling PS controller support in Steam. And ticking kill steam on connect. Problem with this is that sometimes actions kind of cancel themselves out, and it then feels that you need to click button repeatedly to make them work. Or for example clicking options buttons, sometimes open settings in the game, but often menu is opened for a split second and then closes. If I kill steam manually, the game (in my case guardians of the galaxy) closes.
When it works though, it feels amazing. Great work dev!

**Comment by Paliverse** [comment]
Hello, I can suggest to switch emulation to OFF if you use steam. You won’t get Double Input then

**Comment by slovenec88** [comment]
Perfect, and controller mode and audio haptics still work. Amazing.
