### ISSUE TITLE
Loading Languages, please wait... stuck forever

### ISSUE THREAD

**Issue by Ranguvar** [Paliverse/DualSenseX#6]
Just trying this app for the first time -- thank you!

Using Windows 10 20H2 x64, DualSenseX 1.2.7 works for me.
The right-click menu in the system tray has proper labels, and the splash screen lets me choose English (United States) despite noting no internet connection to get other languages.

Newer versions than 1.2.7 instead have placeholder names in the system tray and the splash screen sits on Loading Languages, please wait... forever.

However, after launching 1.2.7 once, now 1.3.1 works just fine.
Neat?

Thanks again!

**Comment by Paliverse** [comment]
so in 1.2.7 no issues? but after its stuck?

**Comment by Ranguvar** [comment]
Yep but once I launch 1.2.7 once now 1.3.1 works

I think 1.3.1 sees Windows NCIS saying "no Internet" and just waits forever
But 1.2.7 while saying can't connect, does seem to install the language pack?
So now 1.3.1 works for me

**Comment by Paliverse** [comment]
hmm weird, im gonna work on a good solution for the setup process, to avoid this mess
