### ISSUE TITLE
program crashed and no longer starts

### ISSUE THREAD

**Issue by kalmaron** [Paliverse/DualSenseX#61]
after changing from xbox360 to dualshock4 the program crashed and no longer starts.  deleted, reinstalled, even reinstalled Windows.  did not help

**Comment by dreamfliper** [comment]
Try to delete temp folder for DualSenseX, for me it's `C:\Temp`, This fix my problem.

**Comment by kalmaron** [comment]
I delete windows.old folder and DualSensX  started. But when i close and try to open again it crash and don't star again. Task Manager show that DualSenseX run

**Comment by Paliverse** [comment]
Only thing I can suggest is deleting the DualSenseX folder located in C:\Temp
