### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by MrHomebrew** [Paliverse/DualSenseX#62]
Noticing high CPU usage with DualsenseX running.

is there any way the program can be optimized to be more effecient?

![Screenshot 2021-11-21 104545](https://user-images.githubusercontent.com/12868874/142768885-b0b7257f-6668-4c37-a980-28610ab99e2c.png)

**Comment by Paliverse** [comment]
Have you tried restarting it? Could sometimes be bugged out. Just incase what are your PC specs?

**Comment by MrHomebrew** [comment]
Yea i did try restarting it and the system noticed same usage patterns.

System has an AMD Ryzen 2500X
32GB Ram
Nvidia 1070
NVME

**Comment by Paliverse** [comment]
Well due to your cpu, you will see some higher usage vs a better cpu etc.. extremely hard to optimize for all PC systems
