### ISSUE TITLE
controller vibration is not working forza horizon 5

### ISSUE THREAD

**Issue by svnshvne** [Paliverse/DualSenseX#63]
Hello, I've connected my dualsense via wire and everything is good except controller vibrations. I don't have them at all (except the lightshow). I tried to set it on the home page, but it's still not working. And another problem, sometimes when I pull the trigger all the way it doesn't show the full power and the game show like I've been pushing it only halfway.

**Comment by Paliverse** [comment]
Check Settings -> Controller Settings -> scroll to bottom and make sure "Disable Controller Vibration" is not toggled on
