### ISSUE TITLE
Power off the gamepad

### ISSUE THREAD

**Issue by Crazik1982** [Paliverse/DualSenseX#65]
Maybe do this, a long press PS button, 10 second press it is to long

**Comment by DamianS-eng** [comment]
How about a way to change the default long press period to power off the controller?

On the by, if Steam is running alongside DualSenseX, you can set up a Steam Chord or desktop binding to turn off the controller in any way, from a specific PS button combination to a shorter long press.

**Comment by Paliverse** [comment]
Currently not supported, you can hold the PS button for 10 secs or configure it through steam to turn off by Pressing PS + Triangle
