### ISSUE TITLE
Pairing 2 dualsenses to 1 PC

### ISSUE THREAD

**Issue by karamba4x** [Paliverse/DualSenseX#68]
Hey there.

Is it possible to pair 2 dualsenses to one PC? simultaneously? I tryed to do that and second controller never wants to connect while first is on.

I used before PS3 controllers with SPC toolkit and it worked fine. I hope it is possible too use 2 controllers of dualsenes at the same time with DualSenseX.

**Comment by Paliverse** [comment]
Currently only one DualSense can be connected at a time, that could change in the future
