### ISSUE TITLE
3rd party Ps5 Joystick not getting connected!! Help

### ISSUE THREAD

**Issue by jtn0xvirus** [Paliverse/DualSenseX#69]

**Comment by jtn0xvirus** [comment]
I bought a Chinese model Ps5 joystick model T.28 and am able to connect using Ds4 in windows. But i am not able to use the haptic feedback and speaker with it. I was not able to connect my joystick using DualSensex software. I really wished there will be a patch or update to support 3rd party Bluetooth joysticks as well.

**Comment by Paliverse** [comment]
Hello, only official DualSense Controllers can be used within the app.

**Comment by jtn0xvirus** [comment]
Please add 3rd party wireless Joystick support which has adaptive trigger
and haptic feedback to be able to work with the app in the next update. It
could be a very amazing update .
Hopefully developers add these support in the coming update releases.
Thanks and Regards.

**Comment by Paliverse** [comment]
Sorry but i will not be adding 3rd party controller support. Only Official DualSense Controllers are supported.

**Comment by jtn0xvirus** [comment]
Bummer!! Sad to hear that.. anyways good luck, it's a matter of time DS4
will be coming up with more haptic feedback and adaptive trigger support,
they already support all bluetooth wireless joysticks ..
