### ISSUE TITLE
Vibration doesn't work on Dolphin

### ISSUE THREAD

**Issue by CreBlaBo** [Paliverse/DualSenseX#7]
I tried to use the vibration motors in the Dolphin Emulator, but Dolphin doesn't show them as available, and they also don't work if i try to manually add them. I don't really know how easy that is to fix, and it isn't really a thing that changes the gaming experience to the negative, but i would prefer to have it working.

**Comment by CreBlaBo** [comment]
btw. it detects the vibration motors just fine with an actual Xbox 360 Controller, it also detects the Dualsense Controller as an Xbox Controller, but like i said, i can't make the vibration motors work with it.

**Comment by Paliverse** [comment]
Hello, ill download Dolphin and test it out. if you have the resources to test out, that would help in finding the cause

**Comment by Paliverse** [comment]
I've figured out how to make the vibration motors work with Dolphin:

● First make sure you download the Beta version, not the stable one. https://dolphin-emu.org/download/
● Then once you Launch Dolphin, press on Controllers top right
● Choose Standard Controller from the dropdown
● Click on Configure
● on the right side middle there should be Rumble and Motor under it
● Click the button to the right of Motor
● A pop up window will display, you will see Motor L and Motor R
● There should be a big white empty box on the bottom that you can type into
● pase this: ``` `Motor L`,`Motor R` ```
● make sure you include the quotes and comma
● Then click on Test, the Controller should vibrate
● If it does, then you can just click on okay and configure the profile to your liking

Enjoy :)
