### ISSUE TITLE
save settings ?

### ISSUE THREAD

**Issue by doriant70** [Paliverse/DualSenseX#70]
Hi friend  cant save my haptic feedback and triggers settings. all reset when start

**Comment by Paliverse** [comment]
Make sure you use the latest version, you can also delete this folder in C:\temp called "DualSenseX" then start the app after

**Comment by doriant70** [comment]
still not working. I want the  left and right  motors on 20 level  but any time that start the app all appears on 100 level again. sorry for  my english

**Comment by Paliverse** [comment]
If you go to Settings -> Controller Settings -> Scroll to the bottom you will see this option "Adjust Motor Strength"
you can make that lower

<img width="835" alt="Screenshot 2021-12-12 164842" src="https://user-images.githubusercontent.com/4289084/145732714-4f499cc0-ebb1-4c17-9168-08d0b9d4aaf9.png">
