### ISSUE TITLE
1.45 not installing, 1.44 works fine but haptic feedback does not

### ISSUE THREAD

**Issue by Razmann4k** [Paliverse/DualSenseX#71]
I had 1.45 installed and working fine when it all of a sudden stopped working. I uninstalled it and tried reinstalling it but the 1.45 installer does not even open. I successfully installed 1.44 but haptic feedback is no longer functional.

**Comment by Paliverse** [comment]
go to C:\Temp\ and delete the folder named DualSenseX

**Comment by Razmann4k** [comment]
Thanks, that fixed it!
