### ISSUE TITLE
Profiles for adaptive triggers

### ISSUE THREAD

**Issue by Elbartoooo** [Paliverse/DualSenseX#72]
I was wondering if it was possible to set up trigger profiles for certain games.. that would automatically switch depending on what game was opened. Love the app 5/5

**Comment by Elbartoooo** [comment]
Also noticed pretty significant cpu usage for a backround process

**Comment by Paliverse** [comment]
Trigger profiles was planned, but i got cought up with working on other projects that i didnt get to implement it. For CPU usage, there's not much i can do about it. my usage is always 0-3%. best thing i can suggest is a restart of the App
