### ISSUE TITLE
Battery % problem

### ISSUE THREAD

**Issue by Romenix** [Paliverse/DualSenseX#75]
Hello, I started to use the dualsensex today, but I don't have a PS5, I use the dualsense only on PC, but the dualsense program don't change the battery %, it´s always on 0%. After that, I unnistalled the program and installed again, now the program shows me 20% but never change, what can I do? I am brazilian, sorry by my english!

**Comment by Paliverse** [comment]
Well the battery level isn't really accurate, It's very hard to get an accurate reading of what percent it is.
