### ISSUE TITLE
Dualsense X can't find my Controller (DS4)

### ISSUE THREAD

**Issue by Chur-Br0th3r** [Paliverse/DualSenseX#76]
the DualSense Controller should auto connect to the App after Installing ViGEmBus and HidHide then restarting PC. I did all of these, but when I launch the app, it says it's searching for my controller, but it never connects. I waited 10 minutes and it still didn't connect.
My PC is Windows 10. The screenshot below is the furthest I've gotten in connecting my DS4 controller to Dualsense X and I don't know what else to do because I downloaded the extra things to auto-connect my controller.

![Screenshot (1)](https://user-images.githubusercontent.com/96139083/146057122-5a5c01f4-3551-45f3-877d-b72206834b48.png)

**Comment by Paliverse** [comment]
I’m sorry but this app is specifically made for the PS5 Controller. Any others aren’t supported

**Comment by begarage** [comment]
@Paliverse I am facing the same issue as mentioned here and both I and the OP have dualsense controllers with ds4 emulation. the controller works fine via USB but does not connect via bluetooth

**Comment by nefarius** [comment]
> update: I connected it via bluetooth (through windows bluetooth connect and not from the dsx app) after putting in pairing mode but then the controller is always connected unless I disable bluetooth. The app now recognizes it but doesn't auto connect like mentioned. Also as a request, perhaps mention how to put the controller in pairing mode somewhere in the app?

Just press and hold the PS button for roughly 10 seconds and the controller shuts off without losing the pairing or having to disable the host.

**Comment by nefarius** [comment]
> the DualSense Controller should auto connect to the App after Installing ViGEmBus and HidHide then restarting PC. I did all of these, but when I launch the app, it says it's searching for my controller, but it never connects. I waited 10 minutes and it still didn't connect.

If you HidHide the DualSense then DualSenseX will ofc. not see it anymore. You can not expect an app that is made for the physical PS**5** controller to work with the virtual PS**4** controller.
