### ISSUE TITLE
Inputlag

### ISSUE THREAD

**Issue by PorciGal** [Paliverse/DualSenseX#79]
Hi, thanks for the GREAT app. I'm loving it.

I got only one problem. Since the att the commands shows some low response.

Could you, please, help it?

**Comment by Paliverse** [comment]
I’m not sure I understand, what’s att?

**Comment by PorciGal** [comment]
actualization

**Comment by Paliverse** [comment]
I'm not sure honestly. I guess maybe reinstall everything and reboot as well
