### ISSUE TITLE
Double inputs with ds4 and x360 mode

### ISSUE THREAD

**Issue by Phenix54s** [Paliverse/DualSenseX#8]
DualsenseX is actually giving double inputs in  games/ software  ,  in any " emulation " mode  unlike  steam/ds4windows tools

meaning in game that reconize  the dualsense   it goes ... pretty wierd( and bad ) 

maybe the  Software don't allow something like  " exclusive mode " like ds4 windows had ?

**Comment by asasuou** [comment]
It is same in win11.
others betterjoyforcemu for joy-con is same multiple inputs, whether it is OS problem?
What is your OS?

**Comment by Phenix54s** [comment]
Still on win10 , other tool like ds4windows don't have that issue with my dualsense controller 

Rewasd works great too without  double inputs

DualsenseX is the only one who has that double input issue  on my side  ... and of course , if i want it .. it's for adaptive trigger support, and that's great ^^'

**Comment by asasuou** [comment]
> Still on win10 , other tool like ds4windows don't have that issue with my dualsense controller
> 
> Rewasd works great too without double inputs
> 
> DualsenseX is the only one who has that double input issue on my side ... and of course , if i want it .. it's for adaptive trigger support, and that's great ^^'

Yes I Agree. I am a user.
Also looking forward to fix the issues.

**Comment by asasuou** [comment]
If just as a ps5 controller, turn the controller emulation to off could fix double input, I think.

**Comment by Phenix54s** [comment]
Turning emulation off makes controls beings messed up with games , because controller is just not supported  correctly everywhere ( yet ) 
until it's fixed, i can't properly use  DualsenseX to it's fullest  :/

**Comment by Paliverse** [comment]
Hello, there is a tool i can implment that will hide the input from the controller and the pc will only read the emulation, however im not to experienced with this tool but ill be taking a look at it soon. its on my list of things to add to hide the input and only show the emulated one

**Comment by Paliverse** [comment]
https://github.com/ViGEm/HidHide/releases/tag/v1.0.30.0

you can install this as a temporary solution to hide the main device and filter out DualSenseX

**Comment by Phenix54s** [comment]
Good to know that you'll check that :D
