### ISSUE TITLE
dualshock 4 emulation bug

### ISSUE THREAD

**Issue by Zephyrus11228** [Paliverse/DualSenseX#82]
DualShock 4 emulation has a bug that instead of just registering a single press of a button (for example right dpad), it will be keep holding it, the xbox 360 emulation and the off (ps5) works just fine, i've tried it on games such as [Fortnite,Warzone,Apex,Cyberpunk, and even on windows the button just keeps on going when i press it ones (Msi gaming laptop running Windows 11 home with all drivers installed)
here's a video of the problem in google drive👇👇👇
[https://drive.google.com/file/d/1YSDVCBwknvBE59pO45rSPBQ6Imvg4AGA/view?usp=sharing](url)

**Comment by Paliverse** [comment]
I know i've seen the bug before, but so hard to trackdown the issue, im currently not seeing the issue when i switched to DualShock emulation. i guess you can do an app settings reset and see if that makes it behave normal again.

**Comment by Paliverse** [comment]
UPDATE: This should be fixed In the next update after some tweaking for the DS4 emulation.

**Comment by Zephyrus11228** [comment]
> I know i've seen the bug before, but so hard to trackdown the issue, im currently not seeing the issue when i switched to DualShock emulation. i guess you can do an app settings reset and see if that makes it behave normal again.

it seems like reinstalling the hidhide driver fixes it sorry to bother you thanks for replying and the amazing work have a fantastic day

**Comment by Paliverse** [comment]
Thank you, but I don’t think that is the issue. I’m most likely taking HidHide out of the app so no further issues. Users can use the app that comes with HidHide to enable it vs the app doing it

**Comment by Zephyrus11228** [comment]
Thanks bud there is no need for that, seems like reinstalling hidhide fixed
the issue

**Comment by Paliverse** [comment]
That's good to hear, im still removing it for other reasons.
