### ISSUE TITLE
Leds didnt turn off

### ISSUE THREAD

**Issue by emilianoscolaro** [Paliverse/DualSenseX#84]
When the PC enters in sleep mode or is shut down, the leds of the Joystick didnt turn off

**Comment by Paliverse** [comment]
You can manually turn it off by unplugging the USB cable or holding the PS button for 10 seconds for BT connection.

**Comment by emilianoscolaro** [comment]
I don't think it's a good idea to unplug the controller every time,I think,the app shoud do that otherwise you arn't killing some proces in the controll
