### ISSUE TITLE
[Feature Request] Linux Support!

### ISSUE THREAD

**Issue by DashCruft** [Paliverse/DualSenseX#85]
DualSenseX is functional for Windows and MacOS only

Would love to see it on linux

**Comment by Paliverse** [comment]
Hmm, not really experienced with Linux or how most things work, and I have multiple things I’m already working on. I’ll take it into consideration

**Comment by DashCruft** [comment]
Thank you for your consideration

**Comment by Etaash-mathamsetty** [comment]
> DualSenseX is functional for Windows and MacOS only
> 
> Would love to see it on linux

you can configure most of the controller through steam, battery level is supported by the linux kernel driver
you can use my project for adaptive triggers (it doesn't look great, but it works): https://github.com/Etaash-mathamsetty/trigger-control

**Comment by Paliverse** [comment]
@Etaash-mathamsetty C++? That’s when I run away lol

**Comment by Etaash-mathamsetty** [comment]
> @Etaash-mathamsetty C++? That’s when I run away lol

you don't have to use c++, I wrote it in c++ because it's the easiest language. (for me)

**Comment by Paliverse** [comment]
> 

Ah okay, well at this time I’m currently focused on DSX so that it can be released on Steam, I will try to take a look when I have some free time
