### ISSUE TITLE
No UI window but dualsensex exists in process list

### ISSUE THREAD

**Issue by MikhailMalyutin** [Paliverse/DualSenseX#87]
After clear first installation all wokrs fine. But after PC reboot or if switch mode to DualShock4 - no any UI window, no icon in tray, but exists DualseneX processes.

Reproduces from version 1.4.1 to 1.4.9. With version 1.4.0 all works fine. If upgrade from 1.4.0 to latest version - no UI window.

After no UI window - I know only one workaround - remove application, clear c:\temp\dualsensex directory, reboot pc and install old version again.

Application was run on very old pc (Core 2 Duo 6300) with Windows 10 with all updates.

**Comment by Paliverse** [comment]
Hlelo, i would suggest staying on 1.4.0, newer libraries might not be supported with your PC making it crash.
