### ISSUE TITLE
[BUG]: Mouse does not works in applications that running by Administrator

### ISSUE THREAD

**Issue by Ivan-Alone** [Paliverse/DualSenseX#89]
**Describe the bug**
Mouse does not working in applications that runs by Administrator (like Genshin Impact that could be runned only by admin) without run DSX as admin. With default run mouse does not works, if run as Admin - all OK.

I think that able to add to app's manifest run as highest available permissions [RunAsHighest]? So it will require run as Admin via UAC if it possible (on administrative users), and just runs in users without adm. permissions

**To Reproduce**
1. Run DSX without any settings
2. Run any application as Administrator 
3. Alt+Tab to it software
4. Touchpad mouse does not working

**Expected behavior**
Working mouse in Admin-runned apps by default

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Browser Firefox (does not matter)

**Comment by Paliverse** [comment]
Hmm interesting, never took that into consideration. I will think about adding run as highest availble, but i don't wnana do that if it keeps asking everytime

**Comment by Paliverse** [comment]
I just set the Highest available, and it's asking everytime. I don't think it's a good idea to have everyone get the pop up everytime if they aren't using the touchpad to mouse for every situation.

**Comment by Ivan-Alone** [comment]
Yes, program must ask it any time when you running it. 
In ds4win it was solved (but I does not tested it) by using additional driver that emulates mouse and keyboard itself (FakerInput) that (as I could understand) running as service, and ds4win itself connects to it through API. 
Highest available was most simple solution as is, but any others exists of course. F.e. require admin only if mousepad is enabled (may add checkbox in settings for admin-runned software support), or at least warn with a pop-up window that in applications launched by admin, the mouse works only when the program is started from the admin.

**Comment by cosmii02** [comment]
Just click properties on dsxwindows and set run as admin in compatiblity tab. No point in making some complex code for it rn
