### ISSUE TITLE
[Feature Request] Automatic controller shutdown on idle

### ISSUE THREAD

**Issue by DashCruft** [Paliverse/DualSenseX#90]
Is there a way that you can implement a feature where if the controller isnt being used after a certain amount of time, it either shuts down or goes to idle so the battery won't be wasted?

**Comment by Ihtiandr141** [comment]
I have the same issue, just exit DualSenseX and turn off bluetooth off and on again, the controller will shut down. Just a workaround at the moment.

**Comment by DashCruft** [comment]
Or just hold the PS5 button for 10s until it shuts down lmao

**Comment by Paliverse** [comment]
Steam has a feature where you can turn off the controller by pressing PS + Triangle. Try it, might already work for you. I do wanna implement a way but it’s not easy to do it. Focusing on gyro for now

**Comment by DashCruft** [comment]
Just tried it. Worked like a charm Thank you

Hopefully this feature will find its way to be implemented in DualSenseX

**Comment by SiTWulf** [comment]
You can check [DS4Windows](https://github.com/Ryochan7/DS4Windows) source code, these feature are implemented and works and you can define the idle time

**Comment by Paliverse** [comment]
I have it figured out already, will be implemented for next update.
