### ISSUE TITLE
when i press my d pad it bugs 

### ISSUE THREAD

**Issue by Ammaarthesweat** [Paliverse/DualSenseX#91]
when i press my d pad it bugs out and thinks im on keyboard and it shoots my gun when i put my cursor on my second monitor its fixed when i also turn off the software its fixed pls fix 

https://user-images.githubusercontent.com/96971822/147869194-1f9ea515-555d-4b32-a456-98f1e16210e1.mp4

**Comment by Paliverse** [comment]
That’s touchpad to mouse, you can disable it in Settings -> Controller Settings -> toggle off “Enable Touchpad to mouse”

**Comment by Ammaarthesweat** [comment]
> That’s touchpad to mouse, you can disable it in Settings -> Controller Settings -> toggle off “Enable Touchpad to mouse”

Thank you so much 🙏 this really helped
