### ISSUE TITLE
Typo on Controller Settings

### ISSUE THREAD

**Issue by LuisMtzGarcia** [Paliverse/DualSenseX#92]
**Describe the bug**
When toggling the Controller Audio System setting, a window appears showing the text "Please unlpug and replug to take effect".

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Controller'
3. Scroll down to 'Controller Audio System'
4. Deactivate Controller Audio System. 
4a. If disabled, activate it and deactivate it to display.
5. Window appears.

**Expected behavior**
Display the text "Please unplug and replug to take  effect".

**Screenshots**
![Typo in window](https://i.imgur.com/k7ZgkbQ.png "Typo")

**Desktop:**
 - OS: Windows 10 Pro 10.0.19042 Build 19042

**Comment by Paliverse** [comment]
Whoops. Thanks for letting me know!
