### ISSUE TITLE
Gyroscope in Detroit Become Human and other games.

### ISSUE THREAD

**Issue by Ihtiandr141** [Paliverse/DualSenseX#93]
**Describe the bug**
Gyroscope doesent work at all.

**To Reproduce**
For example there is one scene that expect you to turn the controller to the right and turning the DualSense to the right - does nothing, But funny enough the whooshing it upwards works in automatic mode (the accelerometer). Tested it multiple times in the same scene, even laid the controller down and it does it by itself.

**Expected behavior**
The gyro should work as intended, in ds4windows it works, but here doesent.

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Version 22000.376

**Additional context**
In ds4windows works gyro as intended but the touchpad doesent work, here the oposite - gyro doesent work but touchpad works.

**Comment by Ihtiandr141** [comment]
BTW - great app, if the gyroscope will work its a nobrainer to choose DualSenseX over everything else!

**Comment by Paliverse** [comment]
Beta test for DualSenseX is available, simply press download, extract, then open the setup. No need to uninstall current version. The link to the download can be found here: <https://github.com/Paliverse/DualSenseX/blob/main/Beta-testing/DualSenseX-Setup.zip>

It includes the following:
```
● Gyro and Accelerometer for DualShock 4 Emulation
- Has flick calibrate threshold adjustment, Example: flicking fast to the left will reset calibrate to the right, meaning the flick direction calibrates to the opposite side of the flick by some margin. It's best being seen when using for aiming. 
- Gyro X Y Z sensitivity adjustments

- Settings for Gyro can be Found in Settings -> Controller Settings

Notes: 
- Gyro has been the only thing tested, Accelerometer has not been tested, but is being sent to the emulation.
- Gyro tested only with the game "Days Gone"

Please provide any feedback regrading Gyro/Accel

● Audio Haptics
- Fixes an issue where the set delay does not take effect when launching the app and/or toggling "Enable Audio Haptics"

```
