### ISSUE TITLE
The controller stopped being detected in windows 10

### ISSUE THREAD

**Issue by Buczixo** [Paliverse/DualSenseX#94]
**Describe the bug**
After update I reconnect the bluetooth controller, the app detrects it, all the settings like triggers or colors of leds are working, but there is no windows "device plugged in" sound and the xbox emulation is no longer detected in games, like in my case Horizon Zero Dawn from Epic. Had to reinstall bluetooth card drivers for some reason, took way longer to fix them i would like to admit.

**To Reproduce**
1. After update, just opwer on the controller like normal
2. App detects controller, but no happy windows noises and no gaming for u

**Expected behavior**
Not working after update

**Comment by Paliverse** [comment]
I don’t think it’s a Bluetooth issue. More of the app needed to be restarted, or ViGEm driver needed to be reinstalled. Other than that, not much I can do as it seems to be a windows related bug
