### ISSUE TITLE
[BUG]: Fix window load pop-up on startup when minimize on tray is on

### ISSUE THREAD

**Issue by DashCruft** [Paliverse/DualSenseX#95]
When DualSenseX minimize on startup feature is toggled on, it shouldn't pop up a load window. Its unnecessarily and not needed.

I'm not sure if this is a bug or not, but it happens to me at least each time I load into windows.

**Comment by Paliverse** [comment]
Should be fixed in the next beta very soon

**Comment by DashCruft** [comment]
I'm very pleased to hear that
