### ISSUE TITLE
[BUG]: DualShock4 emulation can not work in games

### ISSUE THREAD

**Issue by SamuelH6** [Paliverse/DualSenseX#96]
**Describe the bug**
After the new update, it seems some problem occured in DualShock4 emulation. The software can read my controller, and know which buttron has been trigger. it works well.  however, when i open the games like 'it takes two' or 'death stranding', there is no response. Meanwhile, Xbox 360 emulation works well in software and games.

**Comment by Paliverse** [comment]
If the game supports reading the DualShock 4 natively it will work without issues. But if the game only supports Xbox 360, you’ll have to switch the emulation.

**Comment by SamuelH6** [comment]
Before the update, the signal can be read in this two games.

**Comment by SamuelH6** [comment]
And i know both two games support dualshock4. Somethings must go wrong.

**Comment by Paliverse** [comment]
Hmm interesting, maybe try reinstalling ViGEm drivers?

**Comment by SamuelH6** [comment]
okay, let me try. thank for replying. Have a nice day~
