### ISSUE TITLE
[Feature Request]: Game Profiles

### ISSUE THREAD

**Issue by maicol07** [Paliverse/DualSenseX#99]
**Is your feature request related to a problem? Please describe.**
I have to change emulation type manually for games that supports only a different type of emulation

**Describe the solution you'd like**
Like DS4Windows, set a profile for a game/executable in order to change colors, keys, emulation type, adaptive triggers values, ...

**Describe alternatives you've considered**
I know there is already the games tab, but that only works for supported games and only for adaptive triggers values

**Comment by Paliverse** [comment]
In the future I would like to setup a profile system. Just not ready yet.
